apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketmind-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketmind-backend
  template:
    metadata:
      labels:
        app: marketmind-backend
    spec:
      containers:
        - name: backend
          image: marketmind-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://dbuser:dbpassword123@postgres:5432/marketmind"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: SECRET_KEY
              value: "supersecretproductiontokenkeychangeinprod"
            - name: MOCK_MODE
              value: "False"
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: marketmind-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: marketmind-backend
  type: ClusterIP
